[package]
name = "bybit-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "bybit"
path = "src/lib.rs"

[dependencies]
ureq = { version = "2", default-features = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
